import React from 'react';

export const styles: { [key: string]: React.CSSProperties } = {
  container: {
    position: 'absolute',
    backgroundColor: '#ffffff',
    border: '1px solid #e8e8e8',
    borderRadius: '12px',
    padding: '8px 12px',
    boxShadow: '0 6px 24px rgba(0, 0, 0, 0.12), 0 0 0 1px rgba(0, 0, 0, 0.05)',
    zIndex: 10000,
    display: 'flex',
    backdropFilter: 'blur(10px)',
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    width: '100%',
  },
  section: {
    display: 'flex',
    alignItems: 'center',
  },
  divider: {
    width: '1px',
    height: '24px',
    backgroundColor: '#e8e8e8',
  },
  buttonGroup: {
    display: 'flex',
    gap: '2px',
    backgroundColor: '#f5f5f5',
    borderRadius: '6px',
    padding: '2px',
  },
  iconButton: {
    width: '32px',
    height: '32px',
    border: 'none',
    borderRadius: '4px',
    backgroundColor: 'transparent',
    cursor: 'pointer',
    fontSize: '15px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    color: '#333',
  },
  iconButtonActive: {
    backgroundColor: '#1890ff',
    color: '#fff',
  },
  inputGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#f5f5f5',
    borderRadius: '6px',
    padding: '4px 8px',
  },
  inputLabel: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#666',
    userSelect: 'none',
  },
  numberInput: {
    width: '40px',
    border: 'none',
    backgroundColor: 'transparent',
    fontSize: '14px',
    padding: '2px 4px',
    textAlign: 'center',
    outline: 'none',
    fontWeight: '500',
    color: '#333',
  },
  textInput: {
    width: '100px',
    border: 'none',
    backgroundColor: 'transparent',
    fontSize: '13px',
    padding: '2px 4px',
    outline: 'none',
    color: '#333',
  },
  colorGroup: {
    display: 'flex',
    gap: '6px',
  },
  colorItem: {
    position: 'relative',
    width: '32px',
    height: '32px',
  },
  colorInput: {
    width: '32px',
    height: '32px',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    padding: '0',
    overflow: 'hidden',
  },
  colorLabel: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '12px',
    fontWeight: '700',
    pointerEvents: 'none',
    color: '#666',
    mixBlendMode: 'difference',
  },
  bgIcon: {
    width: '14px',
    height: '14px',
    border: '2px solid currentColor',
    borderRadius: '2px',
  },
  sliderGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: '#f5f5f5',
    borderRadius: '6px',
    padding: '4px 8px',
  },
  sliderLabel: {
    fontSize: '14px',
    color: '#666',
    userSelect: 'none',
  },
  rangeInput: {
    width: '70px',
    height: '4px',
    cursor: 'pointer',
    appearance: 'none',
    background: 'linear-gradient(to right, #1890ff 0%, #1890ff var(--value), #e0e0e0 var(--value), #e0e0e0 100%)',
    borderRadius: '2px',
    outline: 'none',
  },
  sliderValue: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#333',
    minWidth: '24px',
    textAlign: 'right',
  },
  deleteButton: {
    width: '32px',
    height: '32px',
    border: 'none',
    borderRadius: '6px',
    backgroundColor: '#fff1f0',
    color: '#ff4d4f',
    cursor: 'pointer',
    fontSize: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    marginLeft: 'auto',
  },
  hint: {
    fontSize: '13px',
    color: '#999',
    padding: '0 8px',
  },
};